controller:
  replicaCount: 1
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 90Mi
  config:
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    proxy-real-ip-cidr: "130.211.0.0/22,35.191.0.0/16,34.159.95.20/32"
  # metrics:
  #   enabled: true
  # podAnnotations:
  #   controller:
  #     metrics:
  #       service:
  #         servicePort: "9090"
  #   prometheus.io/port: "10254"
  #   prometheus.io/scrape: "true"
