---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imgress-mq
  namespace: mq
spec:
  serviceName: imgress-mq
  replicas: 1
  selector:
    matchLabels:
      app: imgress-mq
  template:
    metadata:
      labels:
        app: imgress-mq
    spec:
      containers:
        - name: imgress-mq
          image: rabbitmq:3-management-alpine
          envFrom:
            - configMapRef:
                name: mq-configmap
            - secretRef:
                name: mq-secret
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: imgress-mq
  namespace: mq
spec:
  selector:
    app: imgress-mq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
